### PR TITLE
add run scripts

### PR DESCRIPTION
**Pull request by IsaackMwenda**
Slight modification to standard run script to switch between kakuma and dadaab pipelines

### CODE REVIEW

**Review by as2388 — COMMENTED** [review]
Why do we need per-project run scripts for this project if we didn't last time?

**Comment by IsaackMwenda** [comment]
> Why do we need per-project run scripts for this project if we didn't last time?
The pipeline crashes when it gets to adding the other projects' coda messages since the data directories are separate for each camp. Have been meaning to update it just didn't get time to.

**Comment by IsaackMwenda** [comment]
> Why do we need per-project run scripts for this project if we didn't last time?
Why do we need per-project run scripts for this project if we didn't last time?
The pipeline crashes when it gets to adding the other projects' coda messages since the data directories are separate. Have been meaning to update it just didn't get time to.

**Comment by as2388** [comment]
Ok. We can add this to the long list of reasons why we need to be able to interact with Coda from Python.

**Review by as2388 — APPROVED** [review]

**Pull request merged**
